export { default as Item1 } from './item1.svg'
export { default as Item2 } from './item2.svg'
export { default as Item3 } from './item3.svg'
export { default as Item4 } from './item4.svg'
export { default as Item5 } from './item5.svg'
export { default as Item6 } from './item6.svg'
